import config from 'config';
const eventsForProject = [
  "project.rename",
  "project.archive",
  "project.unarchive",
  "project.member.create",
  "project.member.remove",
  "project.fork",
  "task.create",
  "task.update",
  "task.remove",
  "task.fork",
  "task.update.executor",
  "task.update.startDate",
  "task.update.dueDate",
  "task.update.priority",
  "task.update.note",
  "task.update.involveMembers",
  "task.update.customfields",
  "task.update.storyPoint",
  "task.update.workTime.totalTime",
  "task.update.workTime.usedTime",
  "task.update.progress",
  "task.update.rating",
  "task.update.taskflowstatus",
  "task.update.scenariofieldconfig",
  "task.rename",
  "task.move",
  "task.done",
  "task.archive",
  "task.unarchive",
  "task.bulk.update.executor",
  "task.bulk.done.by.sprint",
  "task.bulk.archive",
  "task.bulk.remove",
  "task.bulk.move",
  "task.bulk.update.sprint",
  "task.bulk.update.dueDate",
  "task.bulk.update.startDate",
  "task.bulk.done.by.sprint",
  "task.bulk.update.stage.by.stage",
  "task.bulk.update.executor.by.stage",
  "task.bulk.update.dueDate.by.stage",
  "task.bulk.update.visibility.by.stage",
  "task.bulk.archive.by.stage",
  "tag.create",
  "tag.remove",
  "post.create",
  "post.update",
  "post.update.involveMembers",
  "post.remove",
  "post.archive",
  "post.unarchive",
  "file.create",
  "file.remove",
  "file.move",
  "file.rename",
  "file.update.version",
  "file.update.involveMembers",
  "file.archive",
  "file.unarchive",
  "event.create",
  "event.remove",
  "event.update",
  "event.update.involveMembers",
  "event.update.customfields",
  "event.archive",
  "event.unarchive",
  "stage.create",
  "stage.rename",
  "taskflowstatus.update",
  "taskflowstatus.create",
  "entry.create",
  "entry.update",
  "entry.update.involveMembers",
  "entry.archive",
  "entry.unarchive",
  "object.like",
  "object.unlike",
  "object.comment",
  "objectlink.create",
  "objectlink.remove",
  "task.on.reminder",
  "event.on.reminder"
];

const eventsForOrganization = [
  "project.create",
  "project.remove",
  "project.archive",
  "project.unarchive",
];

const callbackUrlOrganization =
  `http://${config.hook_host}:${config.port}/callback/organization`;
const callbackUrlProject =
  `http://${config.hook_host}:${config.port}/callback/project`;

export { 
  eventsForProject,
  eventsForOrganization,
  callbackUrlOrganization,
  callbackUrlProject
}


